// <auto-generated />
using System;
using LibraryManagement.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "English novelist",
                            DateOfBirth = new DateTime(1903, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "British author",
                            DateOfBirth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Famous mystery writer",
                            DateOfBirth = new DateTime(1890, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "American novelist",
                            DateOfBirth = new DateTime(1896, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        });
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Dystopian novel",
                            ISBN = "9780451524935",
                            PublicationYear = 1949,
                            Quantity = 5,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "Political satire",
                            ISBN = "9780451526342",
                            PublicationYear = 1945,
                            Quantity = 4,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "Fantasy novel",
                            ISBN = "9780439708180",
                            PublicationYear = 1997,
                            Quantity = 10,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Description = "Fantasy novel",
                            ISBN = "9780439064873",
                            PublicationYear = 1998,
                            Quantity = 8,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Description = "Mystery novel",
                            ISBN = "9780062693662",
                            PublicationYear = 1934,
                            Quantity = 3,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Description = "Mystery novel",
                            ISBN = "9780062073488",
                            PublicationYear = 1937,
                            Quantity = 3,
                            Title = "Death on the Nile"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Description = "Classic novel",
                            ISBN = "9780743273565",
                            PublicationYear = 1925,
                            Quantity = 6,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            Description = "Classic novel",
                            ISBN = "9780684801544",
                            PublicationYear = 1934,
                            Quantity = 5,
                            Title = "Tender Is the Night"
                        });
                });

            modelBuilder.Entity("BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PatronId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PatronId");

                    b.ToTable("BorrowRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 1, 12, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2658),
                            DueDate = new DateTime(2026, 2, 11, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2661),
                            PatronId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            BorrowDate = new DateTime(2026, 1, 17, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2664),
                            DueDate = new DateTime(2026, 2, 16, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2666),
                            PatronId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            BorrowDate = new DateTime(2026, 1, 20, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2667),
                            DueDate = new DateTime(2026, 2, 19, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2667),
                            PatronId = 3,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Patrons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            MembershipDate = new DateTime(2025, 1, 22, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2628)
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            MembershipDate = new DateTime(2025, 7, 22, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2634)
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            MembershipDate = new DateTime(2025, 11, 22, 21, 52, 9, 625, DateTimeKind.Utc).AddTicks(2639)
                        });
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BorrowRecord", b =>
                {
                    b.HasOne("Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patron", "Patron")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Patron", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
